version: "3"

services:

  mongo0:
    image: mongo
    networks:
      mongo_network:
        ipv4_address: 172.16.238.10
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - $HOME/mongodata/mongo0/data:/data/db

  mongo1:
    image: mongo
    networks:
      mongo_network:
        ipv4_address: 172.16.238.11
    ports:
      - 27018:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - $HOME/mongodata/mongo1/data:/data/db

  mongo2:
    image: mongo
    networks:
      mongo_network:
        ipv4_address: 172.16.238.12
    ports:
      - 27019:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - $HOME/mongodata/mongo2/data:/data/db

networks:
  mongo_network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
